site_name: tabular2mcap
site_url: https://alloyrobotics.github.io/tabular2mcap/
repo_url: https://github.com/alloyrobotics/tabular2mcap

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - API Reference:
    - Main API: api/main.md
    - Converter Modules: api/converter.md
    - Schema Management: api/schemas.md
    - Data Models: api/loader.md
  - Contributing: contributing.md

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables
